let bookmarks=JSON.parse(localStorage.getItem("litprep_bookmarks")||"[]");let currentFilter="All";let query="";let mock=[];let mockIndex=0;let mockAnswers={};let seconds=1200;let timerId=null;
const $=s=>document.querySelector(s);
function save(){localStorage.setItem("litprep_bookmarks",JSON.stringify(bookmarks))}
function isSaved(id){return bookmarks.includes(id)}
function toggleBookmark(id){id=String(id);bookmarks=isSaved(id)?bookmarks.filter(x=>x!==id):[...bookmarks,id];save();renderAll()}
function renderFilters(){let areas=["All",...new Set(TOPICS.map(x=>x.area))];$("#topicFilters").innerHTML=areas.map(a=>`<button class="chip ${a===currentFilter?"active":""}" onclick='setFilter(${JSON.stringify(a)})'>${a}</button>`).join("")}
function setFilter(a){currentFilter=a;renderAll()}
function renderTopics(){let list=TOPICS.filter((x,i)=>currentFilter==="All"||x.area===currentFilter).filter(x=>(x.title+" "+x.area+" "+x.description).toLowerCase().includes(query.toLowerCase())).slice(0,220);$("#topicGrid").innerHTML=list.map((x,i)=>{let id="t"+TOPICS.indexOf(x);return `<article class="card"><span class="meta">${x.area} • ${x.level}</span><h3>${x.title}</h3><p>${x.description}</p><div class="card-actions"><button class="mini" onclick='alert(${JSON.stringify(x.title+"\\n\\n"+x.description+"\\n\\nRevision tip: connect this topic to chronology, author-work matching and critical terminology.")})'>Open notes</button><button class="mini bookmark" aria-label="bookmark" onclick='toggleBookmark(${JSON.stringify(id)})'>${isSaved(id)?"★":"☆"}</button></div></article>`}).join("")||"<p>No matching topics.</p>"}
function renderAuthors(){let list=AUTHORS.filter(x=>(x.name+" "+x.period+" "+x.focus+" "+x.works).toLowerCase().includes(query.toLowerCase()));$("#authorGrid").innerHTML=list.map((x,i)=>{let id="a"+i;return `<article class="card"><span class="meta">${x.period}</span><h3>${x.name}</h3><p>${x.focus}</p><div class="author-work"><b>Key works:</b> ${x.works}</div><div class="card-actions" style="margin-top:12px"><button class="mini" onclick='alert(${JSON.stringify(x.name+"\\n\\nPeriod: "+x.period+"\\nFocus: "+x.focus+"\\nKey works: "+x.works)})'>Study author</button><button class="mini bookmark" onclick='toggleBookmark(${JSON.stringify(id)})'>${isSaved(id)?"★":"☆"}</button></div></article>`}).join("")}
function renderTimeline(){$("#timelineBox").innerHTML=TIMELINE.map(x=>`<article class="time-item"><b>${x.date}</b><h3>${x.period}</h3><p>${x.note}</p></article>`).join("")}
function renderPractice(){let qs=QUESTIONS.slice(0,10);$("#practiceBox").innerHTML=`<form id="practiceForm">${qs.map((x,i)=>`<div class="question"><h3>${i+1}. ${x.question}</h3>${x.options.map((o,j)=>`<label class="option"><input type="radio" name="p${i}" value="${j}"> ${o}</label>`).join("")}<div class="explain" id="e${i}">Correct answer: ${x.answer}</div></div>`).join("")}<div class="quiz-actions"><button class="btn dark" type="button" onclick="gradePractice()">Check score</button><span id="practiceScore" class="score"></span></div></form>`}
function gradePractice(){let s=0;QUESTIONS.slice(0,10).forEach((x,i)=>{let p=document.querySelector(`input[name=p${i}]:checked`);if(p&&x.options[+p.value]===x.answer)s++;$("#e"+i).style.display="block"});$("#practiceScore").textContent=`Score: ${s}/10`}
function renderBookmarks(){let items=[];bookmarks.forEach(id=>{if(id.startsWith("t")){let x=TOPICS[+id.slice(1)];if(x)items.push(`<article class="card"><span class="meta">${x.area}</span><h3>${x.title}</h3><p>${x.description}</p><button class="mini" onclick='toggleBookmark(${JSON.stringify(id)})'>Remove bookmark</button></article>`)}else if(id.startsWith("a")){let x=AUTHORS[+id.slice(1)];if(x)items.push(`<article class="card"><span class="meta">${x.period}</span><h3>${x.name}</h3><p>${x.focus}</p><button class="mini" onclick='toggleBookmark(${JSON.stringify(id)})'>Remove bookmark</button></article>`)}});$("#bookmarksBox").innerHTML=items.length?`<div class="grid">${items.join("")}</div>`:"<p class='saved-empty'>No bookmarks yet. Use ☆ on topics or authors to save them here.</p>"}
function renderAll(){renderFilters();renderTopics();renderAuthors();renderTimeline();renderPractice();renderBookmarks()}
$("#search").addEventListener("input",e=>{query=e.target.value;renderTopics();renderAuthors()});$("#clear").onclick=()=>{$("#search").value="";query="";renderTopics();renderAuthors()};
$("#menu").onclick=()=>$("#nav").classList.toggle("open");document.querySelectorAll("nav a").forEach(a=>a.onclick=()=>$("#nav").classList.remove("open"));
function startMock(){clearInterval(timerId);mock=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,20);mockIndex=0;mockAnswers={};seconds=1200;$("#mockResult").innerHTML="";renderMock();timerId=setInterval(()=>{seconds--;updateTimer();if(seconds<=0){clearInterval(timerId);finishMock()}},1000);updateTimer()}
function updateTimer(){let m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("#timer").textContent=m+":"+s}
function renderMock(){if(mockIndex>=mock.length){finishMock();return}let x=mock[mockIndex];$("#mockBox").innerHTML=`<div class="mock-progress"><span style="width:${(mockIndex/mock.length)*100}%"></span></div><div class="mock-q"><p class="kicker">QUESTION ${mockIndex+1} OF ${mock.length}</p><h3>${x.question}</h3>${x.options.map((o,j)=>`<label class="option"><input type="radio" name="m" value="${j}" ${mockAnswers[mockIndex]===j?"checked":""}> ${o}</label>`).join("")}<div class="mock-nav"><button class="btn light" onclick="prevMock()" ${mockIndex===0?"disabled":""}>Previous</button><button class="btn dark" onclick="nextMock()">${mockIndex===mock.length-1?"Finish":"Next"}</button></div></div>`}
function capture(){let p=document.querySelector('input[name="m"]:checked');if(p)mockAnswers[mockIndex]=+p.value}
function nextMock(){capture();mockIndex++;renderMock()}function prevMock(){capture();mockIndex--;renderMock()}
function finishMock(){capture();clearInterval(timerId);let score=0;mock.forEach((x,i)=>{if(mockAnswers[i]!==undefined&&x.options[mockAnswers[i]]===x.answer)score++});$("#mockBox").innerHTML="";$("#mockResult").innerHTML=`<div class="result"><h3>Mock complete</h3><p>Your score: <strong>${score}/${mock.length}</strong> (${Math.round(score/mock.length*100)}%).</p><p>Use the topic and author library to revise weak areas, then restart the mock.</p></div>`}
$("#startMock").onclick=startMock;renderAll();updateTimer();